# Server configuration
server:
  port: 8080

# Spring application name
spring:
  application:
    name: basic-saml
  cloud:
    gateway:
      mvc:
        routes:
          - id: google-route
            uri: https://www.google.com
            predicates:
              - Path=/gate/**

# JWT Configuration
jwt:
  # Secret key used to sign the JWT tokens (should be at least 32 characters)
  secret: ${JWT_SECRET:defaultSecretKeyWhichShouldBeAtLeast32CharactersLong}
  # Token expiration time in milliseconds (default: 1 hour)
  expiration: ${JWT_EXPIRATION:3600000}

# Logging configuration
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        security.saml2: DEBUG
        cloud.gateway: DEBUG
        web.reactive.function.client: DEBUG
        http.server.reactive: DEBUG
